import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "coverage",
      "playwright-report",
      "test-results",
      // Auto-generated by the MCP Vite plugin; rewritten on every build.
      "src/routes/mcp.ts",
      "src/routes/\\[.mcp\\]/**",
      "src/routes/\\[.well-known\\]/**",
      // Generated Supabase integration files (.prettierignore explains why).
      // Linting them means a regeneration can turn CI red on an unrelated
      // change — a generated prefer-const did exactly that.
      "src/integrations/supabase/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // react-hooks 7 (forced by ESLint 10) added React Compiler rules that flag
      // ~77 existing sites. Rewriting timing and card code inside a dependency
      // bump is too risky, so they warn for gradual cleanup instead of failing CI.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      // className composition in this app is cn(), and `"base " + (cond ? …)` is
      // not the same thing: cn() resolves a conditional colour against a base
      // size through tailwind-merge rather than gluing them. Eighteen sites had
      // drifted to the `+` form before DeepSource counted them (JS-R1004); this
      // is what stops the nineteenth.
      //
      // A template literal counts as a string literal to this rule, so a message
      // wrapped across lines stays legal — it only fires when some operand is
      // neither: a call, a ternary, an identifier.
      "prefer-template": "error",
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  eslintPluginPrettier,
);
