/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as LiveRouteImport } from './routes/live'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TvRouteImport } from './routes/tv'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as PlayersPackRouteImport } from './routes/players.pack'
import { Route as PlayersShopRouteImport } from './routes/players.shop'
import { Route as PlayersTradeRouteImport } from './routes/players.trade'
import { Route as RecapSlugRouteImport } from './routes/recap.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPackRoute = PlayersPackRouteImport.update({
  id: '/players/pack',
  path: '/players/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersShopRoute = PlayersShopRouteImport.update({
  id: '/players/shop',
  path: '/players/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTradeRoute = PlayersTradeRouteImport.update({
  id: '/players/trade',
  path: '/players/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapSlugRoute = RecapSlugRouteImport.update({
  id: '/recap/$slug',
  path: '/recap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/league': typeof LeagueRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/shop': typeof PlayersShopRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players/': typeof PlayersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/league': typeof LeagueRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/shop': typeof PlayersShopRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players': typeof PlayersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/league': typeof LeagueRoute
  '/live': typeof LiveRoute
  '/mcp': typeof McpRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/shop': typeof PlayersShopRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players/': typeof PlayersIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/league'
    | '/live'
    | '/mcp'
    | '/order'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/players/$id'
    | '/players/pack'
    | '/players/shop'
    | '/players/trade'
    | '/recap/$slug'
    | '/players/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/league'
    | '/live'
    | '/mcp'
    | '/order'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/players/$id'
    | '/players/pack'
    | '/players/shop'
    | '/players/trade'
    | '/recap/$slug'
    | '/players'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/league'
    | '/live'
    | '/mcp'
    | '/order'
    | '/tv'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/players/$id'
    | '/players/pack'
    | '/players/shop'
    | '/players/trade'
    | '/recap/$slug'
    | '/players/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  ClaimRoute: typeof ClaimRoute
  DraftRoute: typeof DraftRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LeagueRoute: typeof LeagueRoute
  LiveRoute: typeof LiveRoute
  McpRoute: typeof McpRoute
  OrderRoute: typeof OrderRoute
  TvRoute: typeof TvRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersPackRoute: typeof PlayersPackRoute
  PlayersShopRoute: typeof PlayersShopRoute
  PlayersTradeRoute: typeof PlayersTradeRoute
  RecapSlugRoute: typeof RecapSlugRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/pack': {
      id: '/players/pack'
      path: '/players/pack'
      fullPath: '/players/pack'
      preLoaderRoute: typeof PlayersPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/shop': {
      id: '/players/shop'
      path: '/players/shop'
      fullPath: '/players/shop'
      preLoaderRoute: typeof PlayersShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/trade': {
      id: '/players/trade'
      path: '/players/trade'
      fullPath: '/players/trade'
      preLoaderRoute: typeof PlayersTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$slug': {
      id: '/recap/$slug'
      path: '/recap/$slug'
      fullPath: '/recap/$slug'
      preLoaderRoute: typeof RecapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  ClaimRoute: ClaimRoute,
  DraftRoute: DraftRoute,
  LeaderboardRoute: LeaderboardRoute,
  LeagueRoute: LeagueRoute,
  LiveRoute: LiveRoute,
  McpRoute: McpRoute,
  OrderRoute: OrderRoute,
  TvRoute: TvRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PlayersIdRoute: PlayersIdRoute,
  PlayersPackRoute: PlayersPackRoute,
  PlayersShopRoute: PlayersShopRoute,
  PlayersTradeRoute: PlayersTradeRoute,
  RecapSlugRoute: RecapSlugRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
