/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LiveRouteImport } from './routes/live'
import { Route as OrderRouteImport } from './routes/order'
import { Route as TvRouteImport } from './routes/tv'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as PlayersPackRouteImport } from './routes/players.pack'
import { Route as PlayersTradeRouteImport } from './routes/players.trade'
import { Route as RecapSlugRouteImport } from './routes/recap.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPackRoute = PlayersPackRouteImport.update({
  id: '/players/pack',
  path: '/players/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersTradeRoute = PlayersTradeRouteImport.update({
  id: '/players/trade',
  path: '/players/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapSlugRoute = RecapSlugRouteImport.update({
  id: '/recap/$slug',
  path: '/recap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/awards': typeof AwardsRoute
  '/claim': typeof ClaimRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/players/pack': typeof PlayersPackRoute
  '/players/trade': typeof PlayersTradeRoute
  '/recap/$slug': typeof RecapSlugRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/tv'
    | '/players/$id'
    | '/players/pack'
    | '/players/trade'
    | '/recap/$slug'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/tv'
    | '/players/$id'
    | '/players/pack'
    | '/players/trade'
    | '/recap/$slug'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/awards'
    | '/claim'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/tv'
    | '/players/$id'
    | '/players/pack'
    | '/players/trade'
    | '/recap/$slug'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  AwardsRoute: typeof AwardsRoute
  ClaimRoute: typeof ClaimRoute
  DraftRoute: typeof DraftRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  OrderRoute: typeof OrderRoute
  TvRoute: typeof TvRoute
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersPackRoute: typeof PlayersPackRoute
  PlayersTradeRoute: typeof PlayersTradeRoute
  RecapSlugRoute: typeof RecapSlugRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/pack': {
      id: '/players/pack'
      path: '/players/pack'
      fullPath: '/players/pack'
      preLoaderRoute: typeof PlayersPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/trade': {
      id: '/players/trade'
      path: '/players/trade'
      fullPath: '/players/trade'
      preLoaderRoute: typeof PlayersTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$slug': {
      id: '/recap/$slug'
      path: '/recap/$slug'
      fullPath: '/recap/$slug'
      preLoaderRoute: typeof RecapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  AwardsRoute: AwardsRoute,
  ClaimRoute: ClaimRoute,
  DraftRoute: DraftRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  OrderRoute: OrderRoute,
  TvRoute: TvRoute,
  PlayersIdRoute: PlayersIdRoute,
  PlayersPackRoute: PlayersPackRoute,
  PlayersTradeRoute: PlayersTradeRoute,
  RecapSlugRoute: RecapSlugRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
