/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecapSlugRouteImport } from './routes/recap.$slug'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapSlugRoute = RecapSlugRouteImport.update({
  id: '/recap/$slug',
  path: '/recap/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/players': typeof PlayersRouteWithChildren
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/recap/$slug': typeof RecapSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/players': typeof PlayersRouteWithChildren
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/recap/$slug': typeof RecapSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/draft': typeof DraftRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/order': typeof OrderRoute
  '/players': typeof PlayersRouteWithChildren
  '/tv': typeof TvRoute
  '/players/$id': typeof PlayersIdRoute
  '/recap/$slug': typeof RecapSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/players'
    | '/tv'
    | '/players/$id'
    | '/recap/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/players'
    | '/tv'
    | '/players/$id'
    | '/recap/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/draft'
    | '/leaderboard'
    | '/live'
    | '/order'
    | '/players'
    | '/tv'
    | '/players/$id'
    | '/recap/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DraftRoute: typeof DraftRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  OrderRoute: typeof OrderRoute
  PlayersRoute: typeof PlayersRouteWithChildren
  TvRoute: typeof TvRoute
  RecapSlugRoute: typeof RecapSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$slug': {
      id: '/recap/$slug'
      path: '/recap/$slug'
      fullPath: '/recap/$slug'
      preLoaderRoute: typeof RecapSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof PlayersRoute
    }
  }
}

interface PlayersRouteChildren {
  PlayersIdRoute: typeof PlayersIdRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersIdRoute: PlayersIdRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  DraftRoute: DraftRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  OrderRoute: OrderRoute,
  PlayersRoute: PlayersRouteWithChildren,
  TvRoute: TvRoute,
  RecapSlugRoute: RecapSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
